// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Infrastructure;

#nullable disable

namespace StudentAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913054417_AddTableNguoiDungRefresh")]
    partial class AddTableNguoiDungRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAPI.Domain.Entities.BoMon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaBoMon")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("maBM");

                    b.Property<string>("TenBoMon")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("tenMon");

                    b.HasKey("Id");

                    b.ToTable("BoMon", (string)null);
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoMonId")
                        .HasColumnType("int")
                        .HasColumnName("boMonId");

                    b.Property<string>("ChuyenNganh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Tên chuyên ngành")
                        .HasColumnName("chuyenNganh");

                    b.Property<string>("MaLop")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("MaLop");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Tên Lớp")
                        .HasColumnName("tenLop");

                    b.HasKey("Id");

                    b.HasIndex("BoMonId")
                        .HasDatabaseName("IX_LopHoc_boMonId");

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiemTB")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diemTb");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("lopHocId");

                    b.Property<string>("MaSV")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("msv");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId")
                        .HasDatabaseName("IX_SinhVien_lopHocId");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.LopHoc", b =>
                {
                    b.HasOne("StudentAPI.Domain.Entities.BoMon", "BoMon")
                        .WithMany("LopHocs")
                        .HasForeignKey("BoMonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__LopHoc__boMonId");

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("StudentAPI.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.SinhVien", b =>
                {
                    b.HasOne("StudentAPI.Domain.Entities.LopHoc", "LopHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK__SinhVien__lopHoc");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.BoMon", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.LopHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("StudentAPI.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
